version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: go-service
    ports:
      - "8001:8001"  # Expose for direct access if needed
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8001/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  service2:
    build: ./service_2
    container_name: python-service
    ports:
      - "8002:8002"  # Expose for direct access if needed
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "8080:8080"
    depends_on:
      - service1
      - service2
    networks:
      - app-network
    volumes:
      - ./nginx/logs:/var/log/nginx  # Mount logs for easier access

networks:
  app-network:
    driver: bridge